### PR TITLE
add logo png for helm chart use

### PR DESCRIPTION
**Pull request by rimusz**

### CODE REVIEW

**Comment by rimusz** [comment]
cc @alexellis

**Comment by alexellis** [comment]
Hey can we call this openfaas_stacked.png and also sign-off the commit? Thank you @rimusz

**Comment by alexellis** [comment]
Hey @rimusz I'm not sure you got my message.. or maybe you're busy over the break.

Does this image help?

https://github.com/openfaas/media/blob/master/OpenFaaS_logo_stacked_opaque.png

**Comment by rimusz** [comment]
yes, this image would do too

**Pull request closed without merging**
